version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    volumes: 
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  app:
    build: .
    command: npm run dockerize_test
    depends_on:
      - selenium