version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    volumes: 
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  app:
    build: .
    command: npm run dockerize_test
    depends_on:
      - selenium

  node:
    container_name: e2e-protractor-test
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
    depends_on:
      - selenium