version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false
    depends_on: 
      - selenium-hub

  node:
    container_name: e2e-tests-container
    build:
      context: .
      dockerfile: ./dockerfile
    command: 
      - npm run dockerize_test
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - chrome